# Generated by Django 4.2.1 on 2023-06-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0004_seed_item_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecategory',
            options={'verbose_name_plural': 'Type Categories'},
        ),
    ]
