# Generated by Django 4.2.1 on 2023-06-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=255),
        ),
    ]
